name: ci
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
    steps:
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v11
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: bazel --bazelrc=.github/github.bazelrc build //...
      - name: Test
        run: bazel --bazelrc=.github/github.bazelrc test //...
