on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: "rules_emscripten-${{ github.ref}}.zip"
          exclusions: '*.git*'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rules_emscripten-${{ github.ref}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}