on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract release_version
        id: extract_release_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/v}
      - name: Archive Release
        run: zip -x .git -r rules_emscripten-${{ steps.extract_release_version.outputs.RELEASE_VERSION }}.zip .
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rules_emscripten-${{ steps.extract_release_version.outputs.RELEASE_VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}