on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract tag name
        id: extract_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Archive Release
        run: zip -r rules_emscripten-${{ steps.extract_tag_name.outputs.TAG_NAME }}.zip .
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rules_emscripten-${{ steps.extract_tag_name.outputs.TAG_NAME }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}