name: Nightly build and test
on:
  schedule:
    # 1 AM UTC every day
    - cron: "0 1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      config: nightly
